kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.runc.options]
    SystemdCgroup = true
nodes:
- role: control-plane
  # Mount /dev/kvm for hardware virtualization support
  extraMounts:
  - hostPath: /dev/kvm
    containerPath: /dev/kvm
  # Enable necessary features for KubeVirt
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        feature-gates: "DevicePlugins=true"
- role: worker
  # Mount /dev/kvm for hardware virtualization support
  extraMounts:
  - hostPath: /dev/kvm
    containerPath: /dev/kvm