on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:

jobs:
  test_action:
    runs-on: ubuntu-latest
    name: Test KinD action
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Kind Action Test
        uses: ./kind
      - name: Get Nodes
        run: kubectl get nodes
      - name: Create POD
        run: kubectl apply -f https://k8s.io/examples/pods/simple-pod.yaml
      - name: Kubevirt Test
        uses: ./kubevirt
      - name: Check pods
        run: kubectl get pods -A
